name: release
on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: rp
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@main
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}